export const dinos = [
    { name: "Tyrannosaurus Rex", 
    description: "One of the most iconic carnivorous dinosaurs, known for its powerful jaws and small, useless arms. Lived in the Cretaceous period.", 
    diet: "Carnivore", 
    era: "Cretaceous", 
    dangerLevel: 5, 
    img: "https://wallpapercave.com/wp/wp6349425.jpg" },
    { name: "Velociraptor", 
    description: "Known for its intelligence and featured in the Jurassic Park franchise. A small, fast carnivore with a sickle-shaped retractable claw. Lived in the Cretaceous period.", 
    diet: "Carnivore", era: "Cretaceous", 
    dangerLevel: 4, 
    img: "https://e0.pxfuel.com/wallpapers/58/356/desktop-wallpaper-velociraptor-blue-jurassic-park-velociraptor.jpg" },
    { name: "Triceratops", 
    description: "A herbivorous dinosaur with three distinctive horns and a frill. Lived in the Cretaceous period.", 
    diet: "Herbivore", era: "Cretaceous", 
    dangerLevel: 2, 
    img: "https://e1.pxfuel.com/desktop-wallpaper/778/601/desktop-wallpaper-triceratops-jurassic-world-evolution-triceratops.jpg" },
    { name: "Stegosaurus", 
    description: "Recognized for its plated back and spiked tail. A herbivore with a distinctive double row of plates along its back. Lived in the Jurassic period.", 
    diet: "Herbivore", 
    era: "Jurassic", 
    dangerLevel: 2, 
    img: "https://media.istockphoto.com/id/1168444910/photo/stegosaurus-forest-scene-3d-illustration.jpg?s=612x612&w=0&k=20&c=Uqm7C-MOQdzcbI6UPOyaVabe76wcpFgb6WLiJqOyUTI=" },
    { name: "Brachiosaurus", 
    description: "A massive, long-necked herbivore with longer front legs than hind legs. Lived in the Jurassic period.", 
    diet: "Herbivore", 
    era: "Jurassic", 
    dangerLevel: 1, 
    img: "https://media.istockphoto.com/id/870596224/photo/couple-of-brachiosaurus-altithorax-and-a-flock-of-pterosaurs-in-a-scenic-late-jurassic.jpg?s=612x612&w=0&k=20&c=X4ztvxwSNkTA77w6kHCtnN67ZPf4Y1fEn32kP-mYm6k=" }
]
